config/routes.rb
Rails.application.routes.draw do
  
  
  resources :user_sessions
  resources :users

get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/about'

  resources :opers

  resources :groups

  resources :instructors

  resources :operations

  resources :areas

  resources :userrs

  resources :onlines

  resources :documents

  resources :areas do 
     resources :operations
  end  

  resources :areas do
    resources :instructors
  end  
    
  resources :groups do
    resources :opers
  end  
   match '/home', to: 'static_pages#home',  via: 'get'
   match '/help',  to: 'static_pages#help',  via: 'get'
   match '/about',   to: 'static_pages#about',  via: 'get'
   match '/contact', to: 'static_pages#contact',  via: 'get'

  

  root :to => 'static_pages#home'
  

end

app/models/oper.rb
class Oper < ActiveRecord::Base
  belongs_to :document
  belongs_to :online
  belongs_to :group

  validates :number_document, :presence => true
  validates :name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  validates :telephone, :presence => true
  #validates :formation, :presence => true
  validates :date_home, :presence => true
  validates :date_end, :presence => true

   def self.search(search, page)
    where(['upper(name) like ?',
    "%#{search}%".upcase]).paginate(page: page, per_page: 1).order("name")
  end
end

app/controllers/opers_controller.rb
class OpersController < ApplicationController
  before_action :set_oper, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /opers
  # GET /opers.json
  def index
    @opers = @group.opers.search(params[:search], params[:page])
  end

  # GET /opers/1
  # GET /opers/1.json
  def show
  end

  # GET /opers/new
  def new
    @oper = Oper.new
  end

  # GET /opers/1/edit
  def edit
  end

  # POST /opers
  # POST /opers.json
  def create
    @oper = Oper.new(oper_params)
    @oper.group_id = @group.id
    respond_to do |format|
      if @oper.save
        format.html { redirect_to group_opers_path(@group), notice: 'Oper was successfully created.' }
        format.json { render :show, status: :created, location: @oper }
      else
        format.html { render :new }
        format.json { render json: @oper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opers/1
  # PATCH/PUT /opers/1.json
  def update
    respond_to do |format|
      if @oper.update(oper_params)
        format.html { redirect_to group_opers_path(@group), notice: 'Oper was successfully updated.' }
        format.json { render :show, status: :ok, location: @oper }
      else
        format.html { render :edit }
        format.json { render json: @oper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opers/1
  # DELETE /opers/1.json
  def destroy
    @oper.destroy
    respond_to do |format|
      format.html { redirect_to group_opers_url(@group), notice: 'Oper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oper
      @group = Group.find(params[:group_id])
      @oper = Oper.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oper_params
      params.require(:oper).permit(:document_id, :number_document, :name, :last_name, :online_id, :direccion, :email, :telephone, :type_formation, :date_home, :date_end, :group_id)
    end
end

app/helpers/opers_helper.rb
module OpersHelper
end

app/views/opers/_form.html.erb
<%= simple_form_for [@group,@oper], :html => { :class => 'form-horizontal' } do |f| %>
<div class="field">
  <%= f.label :Documento %><br>
  <%= f.text_field :document_id %>
  <%= error_span(@oper[:document_id]) %>
</div>
<div class="field">  
  <%= f.label :Numero_documento %><br>
  <%= f.text_field :number_document %>
  <%= error_span(@oper[:number_document]) %>
</div>
<div class="field">  
  <%= f.label :Nombres %><br>
  <%= f.text_field :name %>
  <%= error_span(@oper[:name]) %>
</div>
<div class="field">  
  <%= f.label :Apellidos %><br>
  <%= f.text_field :last_name %>
  <%= error_span(@oper[:last_name]) %>
</div>
<div class="field"> 
  <%= f.label :Lineas %><br>
  <%= f.text_field :online_id %>
  <%= error_span(@oper[:online_id]) %>
</div>
<div class="field">
  <%= f.label :Direccion %><br>  
  <%= f.text_field :direccion %>
  <%= error_span(@oper[:direccion]) %>
</div>
<div class="field">
  <%= f.label :Email %><br>
  <%= f.text_field :email %>
  <%= error_span(@oper[:email]) %>
</div>
<div class="field"> 
  <%= f.label :Telefono %><br> 
  <%= f.text_field :telephone %>
  <%= error_span(@oper[:telephone]) %>
</div>  
  <%= f.label :Formacion %><br>
  <%= f.text_field :type_formation %>
  <%= error_span(@oper[:type_formation]) %>
<div class="field">  
  <%= f.label :Fecha_Inicio %><br>
  <%= f.text_field :date_home, class: 'datepicker' %>
  <script type="text/javascript">
      $('.datepicker').datepicker({
        language: "es",
        format: "yyyy/mm/dd",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        todayHighlight: true
      });
  </script>
  <%= error_span(@oper[:date_home]) %>
</div>
<div class="field"> 
  <%= f.label :Fecha_fin %><br> 
  <%= f.text_field :date_end, class: 'datepicker' %>
  <script type="text/javascript">
      $('.datepicker').datepicker({
        language: "es",
        format: "yyyy/mm/dd",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        todayHighlight: true
      });
  </script>
  <%= error_span(@oper[:date_end]) %>
</div>
<div class="field"> 
  <%= f.label :Grupo %><br> 
  <%= f.text_field :group_id %>
  <%= error_span(@oper[:group_id]) %>
</div>  
<div class="actions">
  <%= f.button :submit, "Crear", :class => 'btn-primary' %>
  <%= link_to t('.cancelar'),
                group_opers_path(@group), :class => 'btn btn-default' %>
</div>               
<% end %>

app/views/opers/edit.html.erb
<%- model_class = Oper -%>
<div class="page-header">
  <h1><%=t 'Editar Operaria', :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/opers/index.html.erb
<%- model_class = Oper -%>
<div class="page-header">
  <h1>Listado de Operarias</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:documento_id) %></th>
      <th><%= model_class.human_attribute_name(:Numero_documento) %></th>
      <th><%= model_class.human_attribute_name(:nombres) %></th>
      <th><%= model_class.human_attribute_name(:apellidos) %></th>
      <th><%= model_class.human_attribute_name(:lineas_id) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:formacion) %></th>
      <th><%= model_class.human_attribute_name(:fecha_inicio) %></th>
      <th><%= model_class.human_attribute_name(:fecha_fin) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @opers.each do |oper| %>
      <tr>
        <td><%= oper.document_id %></td>
        <td><%= oper.number_document %></td>
        <td><%= oper.name %></td>
        <td><%= oper.last_name %></td>
        <td><%= oper.online_id %></td>
        <td><%= oper.direccion %></td>
        <td><%= oper.email %></td>
        <td><%= oper.telephone %></td>
        <td><%= oper.type_formation %></td>
        <td><%= oper.date_home %></td>
        <td><%= oper.date_end %></td>
        <td>
           <%= link_to t('.Editar'),edit_group_oper_path(@group,oper), :class => 'btn btn-danger' %>
          <%= link_to t('.Eliminar'),group_oper_path(@group,oper), :method => :delete,:data => {:confirm => t('.confirm',:default => t("helpers.links.confirm", :default =>'Are you sure?'))},:class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.nuevo'),
            new_group_oper_path(@group),
            :class => 'btn btn-primary' %>

<%= link_to 'Atras', groups_path , :class => 'btn btn-primary' %>
<br>

<%= will_paginate @opers, renderer: BootstrapPagination::Rails %>
<br>
Operarias: <%= @opers.count %>

app/views/opers/new.html.erb
<div class="page-header">
  <h1>Nueva Operaria</h1>
</div>
<%= render  'form' %>

app/views/opers/show.html.erb
<%- model_class = Oper -%>
<div class="page-header">
  <h1>Operaria</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:documento_id) %>:</strong></dt>
  <dd><%= @oper.document_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numbero_document) %>:</strong></dt>
  <dd><%= @oper.number_document %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @oper.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @oper.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:online_id) %>:</strong></dt>
  <dd><%= @oper.online_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @oper.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @oper.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telephone) %>:</strong></dt>
  <dd><%= @oper.telephone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_formation) %>:</strong></dt>
  <dd><%= @oper.type_formation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_home) %>:</strong></dt>
  <dd><%= @oper.date_home %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_end) %>:</strong></dt>
  <dd><%= @oper.date_end %></dd>
  <dt><strong><%= model_class.human_attribute_name(:group_id) %>:</strong></dt>
  <dd><%= @oper.group_id %></dd>
</dl>

<%= link_to t('.Editar'),edit_oper_path(oper), :class => 'btn btn-primary' %> |
<%= link_to t('.Atras'),oper_path(oper), :class => 'btn btn-primary'