config/routes.rb
Rails.application.routes.draw do
  
  
  resources :user_sessions
  resources :users

get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/about'

  resources :opers

  resources :groups

  resources :instructors

  resources :operations

  resources :areas

  resources :userrs

  resources :onlines

  resources :documents

  resources :areas do 
     resources :operations
  end  

  resources :areas do
    resources :instructors
  end  
    
  resources :groups do
    resources :opers
  end  
   match '/home', to: 'static_pages#home',  via: 'get'
   match '/help',  to: 'static_pages#help',  via: 'get'
   match '/about',   to: 'static_pages#about',  via: 'get'
   match '/contact', to: 'static_pages#contact',  via: 'get'

  

  root :to => 'static_pages#home'
  

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :document
  belongs_to :area
  belongs_to :userr
  belongs_to :online

  #paginacion

  def self.search(search, page)
		where(['upper(name) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 2).order("name")
  end

  #validates :number_document, :presence => true
  validates :name, :presence => true
  validates :gender, :presence => true
  validates :email, :presence => true
  validates :last_name, :presence => true


end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = @area.instructors.search(params[:search], params[:page])
    #@instructors = Instructor.search(params[:search], params[:page])
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)
    @instructor.area_id = @area.id
    respond_to do |format|
      if @instructor.save
        format.html { redirect_to area_instructors_path(@area), notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to area_instructors_path(@area), notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to area_instructors_url(@area), notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @area = Area.find(params[:area_id])
      @instructor = Instructor.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:document_id, :number_documnet, :name, :last_name, :gender, :email, :telephone, :area_id, :userr_id, :online_id)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= simple_form_for [@area,@instructor], :html => { :class => 'form-horizontal' } do |f| %>
<div class="field">
  <%= f.label :Documento %><br>
  <%= f.text_field :document_id %>
  <%= error_span(@instructor[:document_id]) %>
</div>
<div class="field">
  <%= f.label :Numero_Documento %><br>  
  <%= f.text_field :number_documnet %>
  <%= error_span(@instructor[:number_documnet]) %>
</div>
<div class="field"
  <%= f.label :Nombres %><br>  
  <%= f.text_field :name %>
  <%= error_span(@instructor[:name]) %>
</div>
<div class="field">
  <%= f.label :Apellidos %><br>  
  <%= f.text_field :last_name %>
  <%= error_span(@instructor[:last_name]) %>
</div>
<div class="field">
  <%= f.label :Genero %><br>  
  <%= f.text_field :gender %>
  <%= error_span(@instructor[:gender]) %>
</div>
<div class="field">
  <%= f.label :Email %><br>  
  <%= f.text_field :email %>
  <%= error_span(@instructor[:email]) %>
</div>
<div class="field">
  <%= f.label :Telefono %><br>  
  <%= f.text_field :telephone %>
  <%= error_span(@instructor[:telephone]) %>
</div>
<div class="field">
  <%= f.label :Area %><br>  
  <%= f.text_field :area_id %>
  <%= error_span(@instructor[:area_id]) %>
</div>
<div class="field">
  <%= f.label :Rol %><br>  
  <%= f.text_field :userr_id %>
  <%= error_span(@instructor[:userr_id]) %>
</div>
<div class="field">
  <%= f.label :Linea %><br>  
  <%= f.text_field :online_id %>
  <%= error_span(@instructor[:online_id]) %>
</div>

<div class="actions">
  <%= f.button :submit, "Guardar" , :class => 'btn-primary' %>
  <%= link_to t('.cancelar'),
                area_instructors_path(@area), :class => 'btn btn-default' %>
</div>                
<% end %>

app/views/instructors/edit.html.erb
<%- model_class = Instructor -%>
<div class="page-header">
  <h1>Editar Instructor</h1>
</div>
<%= render :partial => 'form' %>

app/views/instructors/index.html.erb
<%- model_class = Instructor -%>
<div class="page-header">
  <h1>Listado de Instructores</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:documento_id) %></th>
      <th><%= model_class.human_attribute_name(:numero_documento) %></th>
      <th><%= model_class.human_attribute_name(:nombres) %></th>
      <th><%= model_class.human_attribute_name(:apellidos) %></th>
      <th><%= model_class.human_attribute_name(:genero) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:area_id) %></th>
      <th><%= model_class.human_attribute_name(:Rol_id) %></th>
      <th><%= model_class.human_attribute_name(:linea_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.document_id %></td>
        <td><%= instructor.number_documnet %></td>
        <td><%= instructor.name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.gender %></td>
        <td><%= instructor.email %></td>
        <td><%= instructor.telephone %></td>
        <td><%= instructor.area.name %></td>
        <td><%= instructor.userr_id %></td>
        <td><%= instructor.online_id %></td>
        <td>
           <%= link_to t('.Editar'),edit_area_instructor_path(@area,instructor), :class => 'btn btn-danger' %>
           <%= link_to t('.Eliminar'),area_instructor_path(@area,instructor), :method => :delete,:data => {:confirm => t('.confirm',:default => t("helpers.links.confirm", :default =>'Are you sure?'))},:class => 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.nuevo'),
            new_area_instructor_path(@area),
            :class => 'btn btn-primary' %>
<%= link_to 'Atras' , areas_path , :class => 'btn btn-primary' %>
<br>

<%= will_paginate @instructors, renderer: BootstrapPagination::Rails %>
<br>
Instructores: <%= @instructors.count %>

app/views/instructors/new.html.erb
<%- model_class = Instructor -%>
<div class="page-header">
  <h1>Nuevo Instructor</h1>
</div>
<%= render :partial => 'form' %>

app/views/instructors/show.html.erb
<%- model_class = Instructor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:document_id) %>:</strong></dt>
  <dd><%= @instructor.document_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number_documnet) %>:</strong></dt>
  <dd><%= @instructor.number_documnet %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @instructor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @instructor.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @instructor.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @instructor.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telephone) %>:</strong></dt>
  <dd><%= @instructor.telephone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:area_id) %>:</strong></dt>
  <dd><%= @instructor.area_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:userr_id) %>:</strong></dt>
  <dd><%= @instructor.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:online_id) %>:</strong></dt>
  <dd><%= @instructor.online_id %></dd>
</dl>


<%= link_to t('.Editar'),edit_instructor_path(instructor), :class => 'btn btn-primary' %> |
<%= link_to t('.Atras'),instructor_path(instructor), :class => 'btn btn-primary'