config/routes.rb
Rails.application.routes.draw do
  
  
  resources :user_sessions
  resources :users

get 'login' => 'user_sessions#new', :as => :login
get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/about'

  resources :opers

  resources :groups

  resources :instructors

  resources :operations

  resources :areas

  resources :userrs

  resources :onlines

  resources :documents

  resources :areas do 
     resources :operations
  end  

  resources :areas do
    resources :instructors
  end  
    
  resources :groups do
    resources :opers
  end  
   match '/home', to: 'static_pages#home',  via: 'get'
   match '/help',  to: 'static_pages#help',  via: 'get'
   match '/about',   to: 'static_pages#about',  via: 'get'
   match '/contact', to: 'static_pages#contact',  via: 'get'

  

  root :to => 'static_pages#home'
  

end

app/models/operation.rb
class Operation < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end
 #  has_attached_file :media, :styles => {
  # :medium => { :geometry => "640x480", :format => 'flv', :convert_options => {:output => {:ar => 44100}} },
   # :large => { :geometry => "1024x576", :format => 'flv', :convert_options => {:output => {:ar => 44100}} },
  #}, :processors => [:ffmpeg]
end
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  belongs_to :area
  validates :name, :presence => true
  validates :description, :presence => true
  validates :machine, :presence => true
  validates :time_stadar, :presence => true

  validates :name, uniqueness: { message: "No se puede Repetir"}
  
   def self.search(search, page)
		where(['upper(name) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 1).order("name")
  end
end
   

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy, :index, :new, :create]

  # GET /operations
  # GET /operations.json
  def index
    @operations = @area.operations.search(params[:search], params[:page])
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)
    @operation.area_id = @area.id
    respond_to do |format|
      if @operation.save
        format.html { redirect_to area_operations_path(@area), notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to area_operations_path(@area), notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to area_operations_url(@area), notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @area = Area.find(params[:area_id])
      @operation = Operation.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:name, :description, :machine, :time_stadar, :image, :area_id)
    end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= simple_form_for [@area,@operation], :html => { :class => 'form-horizontal' } do |f| %>
<div class="field">
  <%= f.label :Nombre %><br>
  <%= f.text_field :name %>
  <%= error_span(@operation[:name]) %>
</div>
<div class="field">
  <%= f.label :Descripcion %><br>  
  <%= f.text_field :description %>
  <%= error_span(@operation[:description]) %>
</div>
<div class="field">  
  <%= f.label :Maquina %><br>
  <%= f.text_field :machine %>
  <%= error_span(@operation[:machine]) %>
</div>
<div>
  <%= f.label :Tiempo_Estandar %><br>  
  <%= f.text_field :time_stadar %>
  <%= error_span(@operation[:time_stadar]) %>
</div>
<div class="field">
  <%= f.label :Imagen %><br>
  <%= f.file_field :image %>
  <%= error_span(@operation[:image]) %>
</div>
<div>
  <%= f.label :Area %><br>  
  <%= f.text_field :area_id %>
  <%= error_span(@operation[:area_id]) %>
</div>

<div class="actions">
  <%= f.button :submit,"Guardar", :class => 'btn-primary' %>
  <%= link_to t('.cancelar'),
               area_operations_path(@area), :class => 'btn btn-default' %>
</div>               
<% end %>

app/views/operations/edit.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1>Editar Operacion</h1>
</div>
<%= render :partial => 'form' %>

app/views/operations/index.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1>Listado de Operaciones</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:maquina) %></th>
      <th><%= model_class.human_attribute_name(:tiempo_estandar) %></th>
      <th><%= model_class.human_attribute_name(:imagen) %></th>
      <th><%= model_class.human_attribute_name(:area_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.name %></td>
        <td><%= operation.description %></td>
        <td><%= operation.machine %></td>
        <td><%= operation.time_stadar %></td>
        <td><%= image_tag operation.image.url(:thumb) %></td>
        <td><%= operation.area.name %></td>
         <td>
       <%= link_to t('.Editar'),
    edit_area_operation_path(@area,operation), :class => 'btn btn-mini' %>
          <%= link_to t('.Eliminar'),
    area_operation_path(@area,operation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Esta Seguro?')) },
    :class => 'btn btn-large btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.nuevo'),
            new_area_operation_path(@area),
            :class => 'btn btn-primary' %>

<%= link_to 'atras' , areas_path , :class => 'btn btn-primary' %>            
<br>

<%= will_paginate @operations, renderer: BootstrapPagination::Rails %>
<br>
Operaciones: <%= @operations.count %>

app/views/operations/new.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1>Nueva Operacion</h1>
</div>
<%= render :partial => 'form' %>

app/views/operations/show.html.erb
<%- model_class = Operation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @operation.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @operation.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:machine) %>:</strong></dt>
  <dd><%= @operation.machine %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time_stadar) %>:</strong></dt>
  <dd><%= @operation.time_stadar %></dd>
  <dd><%= image_tag @product.image.url(:medium) %>:</strong></dt>
  <dt><strong><%= model_class.human_attribute_name(:area_id) %>:</strong></dt>
  <dd><%= @operation.area_id %></dd>
</dl>

<%= link_to t('.Editar'),edit_operation_path(operation), :class => 'btn btn-primary' %> |
<%= link_to t('.Atras'),operation_path(operation), :class => 'btn btn-primary'

<%= link_to t('.Eliminar'),
              operation_path(@operation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>